Algoritmo "Dolar_para_real"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo Olmedo dos Santos
// Data atual  : 07/05/2022
Var
// Seção de Declarações das variáveis 
   moedaReal: real
   moedaDolar: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Dolar:")
   leia (moedaDolar)
   moedaReal<- moedaDolar*3.25
   escreval ("Real:", moedaReal)


Fimalgoritmo